// This file is generated by scripts/generate-gallery-manifest.mjs.
// Run `npm run generate:gallery` after changing files in public/gallery.

export const galleryItems = [
  {
    "id": "20260207_190927",
    "src": "/gallery/20260207_190927.jpg",
    "alt": "20260207 190927",
    "title": "20260207 190927"
  },
  {
    "id": "Untitled76_20260112085521",
    "src": "/gallery/Untitled76_20260112085521.jpg",
    "alt": "Untitled76 20260112085521",
    "title": "Untitled76 20260112085521"
  },
  {
    "id": "Henry_20251122171520",
    "src": "/gallery/Henry_20251122171520.png",
    "alt": "Henry 20251122171520",
    "title": "Henry 20251122171520"
  },
  {
    "id": "Untitled58_20251106204032",
    "src": "/gallery/Untitled58_20251106204032.png",
    "alt": "Untitled58 20251106204032",
    "title": "Untitled58 20251106204032"
  },
  {
    "id": "20250918_213846",
    "src": "/gallery/20250918_213846.jpg",
    "alt": "20250918 213846",
    "title": "20250918 213846"
  },
  {
    "id": "20250905_204525",
    "src": "/gallery/20250905_204525.jpg",
    "alt": "20250905 204525",
    "title": "20250905 204525"
  },
  {
    "id": "20250829_234240",
    "src": "/gallery/20250829_234240.jpg",
    "alt": "20250829 234240",
    "title": "20250829 234240"
  },
  {
    "id": "20250814_173428",
    "src": "/gallery/20250814_173428.jpg",
    "alt": "20250814 173428",
    "title": "20250814 173428"
  },
  {
    "id": "20250617_105331",
    "src": "/gallery/20250617_105331.jpg",
    "alt": "20250617 105331",
    "title": "20250617 105331"
  },
  {
    "id": "20250601_095311",
    "src": "/gallery/20250601_095311.jpg",
    "alt": "20250601 095311",
    "title": "20250601 095311"
  },
  {
    "id": "20250325_115431",
    "src": "/gallery/20250325_115431.jpg",
    "alt": "20250325 115431",
    "title": "20250325 115431"
  },
  {
    "id": "IMG_20250208_165752_393",
    "src": "/gallery/IMG_20250208_165752_393.jpg",
    "alt": "IMG 20250208 165752 393",
    "title": "IMG 20250208 165752 393"
  },
  {
    "id": "20240807_123326",
    "src": "/gallery/20240807_123326.jpg",
    "alt": "20240807 123326",
    "title": "20240807 123326"
  },
  {
    "id": "20240731_151130",
    "src": "/gallery/20240731_151130.jpg",
    "alt": "20240731 151130",
    "title": "20240731 151130"
  },
  {
    "id": "20240611_130556",
    "src": "/gallery/20240611_130556.jpg",
    "alt": "20240611 130556",
    "title": "20240611 130556"
  },
  {
    "id": "Screenshot_20240419_111730_Gallery",
    "src": "/gallery/Screenshot_20240419_111730_Gallery.jpg",
    "alt": "Screenshot 20240419 111730 Gallery",
    "title": "Screenshot 20240419 111730 Gallery"
  },
  {
    "id": "Untitled66 (4)",
    "src": "/gallery/Untitled66%20(4).png",
    "alt": "Untitled66 (4)",
    "title": "Untitled66 (4)"
  }
]
